# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f143e0a00f84f238dd5e8840daeeb365c65c167b55dcaf37186e9ab838a75102286ff8b9606bb04b96f33045d1eb4c12c0f0cb1adcb7a8fb470aa82cb47bf5

test:
  secret_key_base: 57a6893035bccd11b51ed062fa1b7e6cdc9591c86fb250a57db33079e5c07139f362c66bcc4f3750e48f29947ab40864213b29ab2ef86f4e8e86f9b05c9b6dbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
